server:
  port: 8081

spring:
  shardingsphere:
    datasource:
      names: master,slave0,slave1
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.100.252:3307/tms_biz?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&useSSL=true&verifyServerCertificate=false
        username: user_biz
        password: jd83j2judm4
      slave0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.100.252:3307/tms_base?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&useSSL=true&verifyServerCertificate=false
        username: user_base
        password: uw82jx7k3oo92yhs
      slave1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.100.252:3307/tms_log?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&useSSL=true&verifyServerCertificate=false
        username: user_log
        password: fjw2ulr8djexi9s
    props:
      sql.show: true
    masterslave:
      load-balance-algorithm-type: round_robin
    sharding:
      master-slave-rules:
        master:
          master-data-source-name: master
          slave-data-source-names: slave0,slave1
  profiles:
    active: dev
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
###
# publisher-confirms: true 监听消息是否 到达 exchange
# publisher-returns: true 监听消息是否 没有到达 queue
# template.mandatory: true 自动删除不可达消息，默认为false
###

mybatis-plus:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: io.github.yehongzhi.model
